#!/usr/bin/env python3

import argparse

argparser = argparse.ArgumentParser(description='yoink - Send unsolicited Neighbor Advertisements or gratuitous ARP')
argparser.add_argument('-i', '--interface', help='src interface')
argparser.add_argument('-l', '--linklocal', help='src link-local IP')
argparser.add_argument('-m', '--mac', help='src MAC')
argparser.add_argument('-t', '--target', help='target IP')
argparser.add_argument('-v', '--verbose', action='store_true', help='Verbose mode')
argparser.add_argument('-w', '--write', help='Write pcap file instead of sending packets out the wire')
args = argparser.parse_args()

if ( not args.interface and not args.write ) or not args.linklocal or not args.mac or not args.target:
  argparser.print_help()
  exit(1)

import scapy.all as scapy
import sys

ether=(scapy.Ether(src=args.mac, dst='33:33:00:00:00:01'))
ipv6=scapy.IPv6(src=args.linklocal, dst='ff02::1')
na=scapy.ICMPv6ND_NA(tgt=args.target, R=0)
lla=scapy.ICMPv6NDOptDstLLAddr(lladdr=args.mac)

if args.verbose:
  (ether/ipv6/na/lla).display()

if args.write:
  scapy.wrpcap(args.write, ether/ipv6/na/lla)

if args.interface:
  scapy.sendp(ether/ipv6/na/lla, iface=args.interface)
